name: gimple
description: A native desktop Gantt chart application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gantt: ^0.9.2
  flutter_quill: ^11.4.1
  intl: ^0.20.2
  collection: ^1.19.1
  flutter_quill_delta_from_html: ^1.5.2
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  